# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name="Ім'я")),
                ('last_name', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Прізвище')),
                ('middle_name', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='По-батькові')),
                ('birthday', models.DateField(blank=True, default='', max_length=256, null=True, verbose_name='Дата народження')),
                ('e_mail', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Електронна пошта')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
        ),
    ]
